services:
  odoo:
    build: .
    command: tail -F anything
    environment:
        - DB_HOST=db
        - DB_USER=odoo
        - DB_NAME=odoo
        - OPENUPGRADE_TARGET_VERSION=16.0
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
